### ISSUE TITLE
 Invalid Type Read: The type 'group-membership:user-group' does not exist.

### ISSUE THREAD

**Issue by estkae** [james-whiteside/typedb-iam-python#3]
I am trying to run the project but I am running into an error:  Invalid Type Read: The type 'group-membership:user-group' does not exist.
I am new could someone solve the project problem in the schema or give me a type.
This query is not executing correctly:
query = ' '.join([
                    'match',
                    '$g isa user-group, has ' + group_identifier + ' "' + group_name + '";', # noqa: E501
                    '$s isa subject, has ' + subject_identifier + ' "' + member_name + '";', # noqa: E501
                    'insert',
                    '$m (user-group: $g, group-member: $s) isa group-membership;'
                ])

**Comment by james-whiteside** [comment]
Hi Karl, this repo is a personal project and not supported by Vaticle. I stopped maintaining it some time ago, but please feel free to continue working on it on your own fork.
